version: '3'

services:
  db:
    image: mysql:5.7
    container_name: rental_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=rental


